# Generated by Django 5.0.1 on 2024-01-28 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friesd',
            new_name='Friend',
        ),
    ]
